imports:
    - php

tools:
    external_code_coverage: false
    php_analyzer: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
            sniffs: { generic: { formatting: { multiple_statement_alignment_sniff: false } } }